import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,//all the page.tsx
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}//removing the html and body tag will give error
      >
        <div className="bg-yellow-300 text-black  p-2">nav from root level layout</div>
        {children}{/*all the page.tsx will have this layout wrapped around*/}
        <div className="bg-yellow-300 text-black  p-2">footer from root level layout</div>
      </body>
    </html>
  );
}
