import NextAuth from "next-auth"
import CredentialsProvider from "next-auth/providers/credentials";

// whatever request come to api/auth/.. will be handle by the next-auth library
//a frontend will be autogenerated on api/auth/signin based on provider passed
const handler = NextAuth({
  providers: [
    CredentialsProvider({
    // The name to display on the sign in form (e.g. "Sign in with...")
    name: "Credentials",
    // `credentials` is used to generate a form on the sign in page.
    // You can specify which fields should be submitted, by adding keys to the `credentials` object.
    // e.g. domain, username, password, 2FA token, etc.
    // You can pass any HTML attribute to the <input> tag through the object.
    credentials: {
      username: { label: "Username", type: "text", placeholder: "soham" },
      password: { label: "Password", type: "password" }
    },
    async authorize(credentials, req) {
      const username = credentials?.username
      const password = credentials?.password
      console.log(username);
      console.log(password);
      
      // Add logic here to look up the user from the credentials supplied
      const user = {
         id: "1",
         name: "Soham Banerjee",
         email: "sohambanerjee384@gmail.com" }

      if (user) {
        return user
      } else {
        // If you return null then an error will be displayed advising the user to check their details.
        return null
      }
    }
  })],
  // secret: "12312"// if u want to use the secret otion you have to declare NEXTAUTH_SECRET in the .env and get the secret from there hardcoding the seceret here will return null when using getServerSession
  //you can add more providers here
})
// returns another func     
//now GET and POST will not be hanfle by developer but by the handler function
export const GET = handler
export const POST = handler